stages:
  load_data:
    cmd: python src/load.py --config=params.yaml
    deps:
    - src/data.py
    - src/load.py
    - dataset/winequality.csv
    outs:
    - data/raw/winequality.csv

  split_data:
    cmd: python src/split.py --config=params.yaml
    deps:
    - src/split.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv   

  train_and_evaluate:
    cmd: python src/train.py --config=params.yaml
    deps:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv 
    - src/train.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio  
    outs:
    - model/model.joblib